export const SEARCH_LOGIN_START = 'SEARCH_LOGIN_START';
export const SEARCH_LOGIN_ERROR = 'SEARCH_LOGIN_ERROR';
export const SEARCH_LOGIN_COMPLETE = 'SEARCH_LOGIN_COMPLETE';

export const SEARCH_USUARIO_BY_ID_START = "SEARCH_USUARIO_BY_ID_START";
export const SEARCH_USUARIO_BY_ID_ERROR = "SEARCH_USUARIO_BY_ID_ERROR";
export const SEARCH_USUARIO_BY_ID_COMPLETE = "SEARCH_USUARIO_BY_ID_COMPLETE";

export const LOAD_SUCURSAL_START = "LOAD_SUCURSAL_START";
export const LOAD_SUCURSAL_ERROR = "LOAD_SUCURSAL_ERROR";
export const LOAD_SUCURSAL_COMPLETE = "LOAD_SUCURSAL_COMPLETE";

export const LOAD_ASIGNACIONES_START = "LOAD_ASIGNACIONES_START";
export const LOAD_ASIGNACIONES_ERROR = "LOAD_ASIGNACIONES_ERROR";
export const LOAD_ASIGNACIONES_COMPLETE = "LOAD_ASIGNACIONES_COMPLETE";

